name: positronic
channels:
  - conda-forge
  - pytorch
  - defaults
dependencies:
  - python=3.11
  # Build tools
  - gcc_linux-64
  - gxx_linux-64
  # Deps

  # These three are needed for libfranka, and then franky
  - poco
  - pcre
  - pinocchio

  - av
  - uvicorn
  - jupyter
  - matplotlib
  - numpy
  - opencv
  - pymodbus
  - pytorch
  - requests
  - scipy
  - uvicorn[standard]
  - pip
  - pyaudio
  - pip:
#    - lerobot  # We use our own fork
    - click
    - cmake-build-extension
    - dearpygui
    - fire
    - hydra-colorlog
    - hydra-core
    - numpy-quaternion
    - pytest
    - pytest-asyncio
    - websockets
    - yappi
    - dm_control
    - pyspacemouse
    - git+https://github.com/lilohuang/PyTurboJPEG.git@v1.7.8
    - linuxpy
    - imageio
    - hydra-zen
    - rerun-sdk
# python /usr/local/zed/get_python_api.py
