[project]
name = "positronic"
version = "0.1.0"
description = "Positronic robotics project"
requires-python = "~=3.11"
dependencies = [
    "numpy",
    "opencv-python-headless",
    "torch",
    "requests",
    "scipy",
    "uvicorn[standard]",
    "click",
    "cmake-build-extension",
    "dearpygui",
    "fire",
    "numpy-quaternion>=2024.0",
    "pytest",
    "pytest-asyncio",
    "websockets",
    "yappi",
    "dm_control",
    "mujoco",
    "pyturbojpeg @ git+https://github.com/lilohuang/PyTurboJPEG.git@v1.7.8",
    "imageio[ffmpeg]",
    "rerun-sdk>=0.23",
    "matplotlib",
    "av",
    "fastapi",
    "ruckig",
    "cvxopt",
]

[project.optional-dependencies]
hardware = [
    "pyaudio",
    "pymodbus",
    "pyspacemouse",
    "linuxpy",
    "pin",  # For Kinova and Tidybot2
    # Tidybot2
    "threadpoolctl==3.5.0",
    "phoenix6==24.3.0",
    "pygame==2.5.2",
    "pyserial", # For DH gripper
]
dev = [
    "jupyter",
    "ipython",
    "opencv-python"
]
lerobot = [
    "einops>=0.8.0",
    "datasets>=2.19.0",
    "torchvision>=0.17.1",
    "diffusers>=0.27.2",
    "h5py>=3.10.0",
    "huggingface-hub>=0.25.0",
    "draccus>=0.10.0",
    "jsonlines>=4.0.0",
]

[tool.pytest.ini_options]
testpaths = [
    "*/tests",
]
python_files = ["test_*.py", "*_test.py"]
