[build-system]
requires = ["setuptools>=68"]
build-backend = "setuptools.build_meta"

[project]
name = "positronic"
version = "0.1.0"
description = "Positronic robotics project"
requires-python = "~=3.11"
dependencies = [
    "av",
    "click",
    "cmake-build-extension",
    "configuronic>=0.2",
    "cvxopt",
    "dearpygui",
    "dm_control",
    "fastapi",
    "fire",
    "imageio[ffmpeg]",
    "matplotlib",
    "mujoco",
    "numpy-quaternion>=2024.0",
    "numpy",
    "opencv-python-headless",
    "pyarrow",
    "pyturbojpeg @ git+https://github.com/lilohuang/PyTurboJPEG.git@v1.7.8",
    "pyyaml",
    "requests",
    "rerun-sdk>=0.23",
    "ruckig",
    "scipy",
    "torch",
    "uvicorn[standard]",
    "websockets",
    "yappi",
]

[project.optional-dependencies]
hardware = [
    "feetech-servo-sdk", # for feetech motors
    "kortex-api @ https://artifactory.kinovaapps.com/artifactory/generic-local-public/kortex/API/2.7.0/kortex_api-2.7.0.post5-py3-none-any.whl; sys_platform == 'linux'",
    "linuxpy",  # For Linux video capture
    "pin",  # For Kinova
    "placo",
    "pyaudio",  # For SoundSystem
    "pymodbus",  # For DH gripper
    "pyserial", # For DH gripper
]
dev = [
    "flake8",
    "ipython",
    "jupyter",
    "opencv-python",
    "pytest-asyncio",
    "pytest",
    "rerun-sdk[notebook]",
]
lerobot = [
    "einops>=0.8.0",
    "datasets>=2.19.0",
    "torchvision>=0.17.1",
    "diffusers>=0.27.2",
    "h5py>=3.10.0",
    "huggingface-hub>=0.25.0",
    "draccus>=0.10.0",
    "jsonlines>=4.0.0",
    "timm"
]

[tool.pytest.ini_options]
testpaths = [
    "pimm/tests",
    "positronic/dataset/tests",
    "positronic/geom/tests",
    "positronic/tests",
]
python_files = ["test_*.py", "*_test.py"]

[tool.setuptools.packages.find]
where = ["."]
include = [
    "positronic*",
    "pimm*",
]
