_target_: positronic.inference.StateEncodingConfig
state_output_key: observation.state
images:
  - key: first.image
    output_key: observation.images.front
    resize:
      - 352
      - 192
  - key: second.image
    output_key: observation.images.back
    resize:
      - 352
      - 192
state:
  - grip
