- _target_: simulator.mujoco.scene.transforms.AddCameras
  additional_cameras:
    side_view:
      pos: [1.235, -0.839, 1.092]
      xyaxes: [0.712, 0.702, -0.000, -0.420, 0.425, 0.802]
    table_view:
      pos: [0.985, -0.008, 0.744]
      xyaxes: [0.003, 1.000, 0.000, -0.855, 0.003, 0.518]
    front_view:
      pos: [1.756, 0.061, 0.850]
      xyaxes: [-0.009, 1.000, 0.000, -0.328, -0.003, 0.945]
    back_view:
      pos: [-0.451, 0.978, 0.629]
      xyaxes: [-0.544, -0.839, -0.000, 0.242, -0.157, 0.958]

- _target_: simulator.mujoco.scene.transforms.AddBox
  name: box_0
  size: [0.02, 0.02, 0.01]
  pos: [0.0, 0.0, 0.0]
  rgba: [1, 0, 0, 1]
  freejoint: true

- _target_: simulator.mujoco.scene.transforms.SetBodyPosition
  body_name: box_0_body
  random_position: [[0.31, -0.28, 0.31], [0.69, 0.28, 0.31]]

- _target_: simulator.mujoco.scene.transforms.AddBox
  name: box_1
  size: [0.02, 0.02, 0.01]
  pos: [0.0, 0.0, 0.01]
  rgba: [0, 1, 0, 1]
  freejoint: true

- _target_: simulator.mujoco.scene.transforms.SetBodyPosition
  body_name: box_1_body
  random_position: [[0.31, -0.28, 0.31], [0.69, 0.28, 0.31]]
