services:
  training:
    build:
      context: ..
      dockerfile: docker/Dockerfile.training
    image: ${IMAGE_REGISTRY}positronic-training:latest
    volumes:
      - /datasets:/datasets:ro
      - /outputs:/outputs
      - ..:/positronic
    working_dir: /positronic
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    environment:
      - CUDA_VISIBLE_DEVICES=${CUDA_VISIBLE_DEVICES:-0}
    stdin_open: true
    tty: true
