"""Replay recorded policy commands and compare simulation-state checkpoints.

Checkpoints are generated by make_replay_fixture.py against this integration. The recording
has an unrecorded command tail (internal#130), so the test covers only the recorded prefix
and makes no assertion about the recorded success result. Missing benchmark assets skip the test.

Run on a box with the asset packs (a GPU-less one uses mesa software EGL)::

    MLSPACES_ASSETS_DIR=... MUJOCO_GL=egl EGL_PLATFORM=surfaceless LIBGL_ALWAYS_SOFTWARE=1 \
        uv run --locked pytest positronic/simulator/molmo_spaces/tests/test_replay.py --no-cov
"""

import os
from pathlib import Path

import numpy as np
import pytest

from positronic.simulator.molmo_spaces import mapping
from positronic.simulator.molmo_spaces.tests import make_replay_fixture as fixture_fields
from positronic.simulator.molmo_spaces.tests.make_replay_fixture import replay_commands

FIXTURES = sorted(Path(__file__).parent.glob('replay_ep*.npz'))

SIM_STATE_TOL = 1e-6  # Absolute tolerance for numeric differences between replay hosts.


def _skip_unless_present(bench: mapping.BenchmarkPath) -> None:
    """Skip unless the asset directory contains the fixture's benchmark manifest."""
    assets = os.environ.get(mapping.ASSETS_DIR_ENV)
    if not assets:
        pytest.skip(f'{mapping.ASSETS_DIR_ENV} is unset — MolmoSpaces asset packs are needed to replay')
    benchmark_dir = bench.under(Path(assets))
    if not (benchmark_dir / mapping.MOLMO_BENCHMARK_MANIFEST).is_file():
        pytest.skip(f'{benchmark_dir} is absent — this asset pack cannot replay the fixture')


@pytest.mark.parametrize('fixture_path', FIXTURES, ids=lambda path: path.stem)
def test_recorded_rollout_replays_the_pinned_trajectory(fixture_path: Path):
    fixture = np.load(fixture_path, allow_pickle=False)
    commands, grips = fixture[fixture_fields.FIELD_COMMANDS], fixture[fixture_fields.FIELD_GRIPS]
    episode_index = int(fixture[fixture_fields.FIELD_EPISODE_INDEX])
    bench = mapping.BenchmarkPath.parse(str(fixture[fixture_fields.FIELD_BENCHMARK_PATH]))
    _skip_unless_present(bench)
    states = replay_commands(bench, episode_index, commands, grips)

    assert len(states) == len(commands), (
        f'replay of episode {episode_index} terminated after {len(states)} of {len(commands)} recorded steps '
        f'(its {int(fixture[fixture_fields.FIELD_UNREPLAYABLE_TAIL_STEPS])} unrecorded tail steps are excluded)'
    )

    checkpoint_steps = fixture[fixture_fields.FIELD_CHECKPOINT_STEPS]
    for step, pinned in zip(checkpoint_steps, fixture[fixture_fields.FIELD_CHECKPOINT_SIM_STATE], strict=True):
        replayed = states[int(step) - 1]  # Fixture steps are 1-based.
        deviation = float(np.max(np.abs(replayed - pinned)))
        assert deviation <= SIM_STATE_TOL, (
            f'sim_state diverged by {deviation:.3e} at step {step} of episode {episode_index}'
        )
