defaults:
  - hardware: franka_mujoco
  - _self_

image_name_mapping:
  front: handcam_front
  back: handcam_back

use_ik: false

input_dir: null
data_output_dir: null

mujoco:
  camera_names:
    - handcam_front
    - handcam_back
