name: Check code style

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Fetch all history for all branches and tags
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install black==25.1
    - name: Check code style for changed files
      run: |
        if [ "${{ github.event_name }}" == "pull_request" ]; then
          # For PRs, compare against the PR base branch
          git diff --name-only --diff-filter=d ${{ github.event.pull_request.base.sha }} ${{ github.sha }} | grep -E "\.py$" | xargs -r black --check --diff --skip-string-normalization
        else
          # For pushes to main, use the previous approach
          git diff --name-only --diff-filter=D origin/main HEAD | grep -E "\.py$" | xargs -r black --check --diff --skip-string-normalization
        fi