name: Check code style

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Fetch all history for all branches and tags
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install black==25.1
    - name: Check code style for changed files
      run: |
        if [ "${{ github.event_name }}" == "pull_request" ]; then
          # For PRs, get the base commit from the PR event
          BASE_SHA=${{ github.event.pull_request.base.sha }}
        else
          # For pushes to main, use the parent commit
          BASE_SHA=$(git rev-parse HEAD^)
        fi

        # Get changed Python files compared to the base commit
        CHANGED_FILES=$(git diff --name-only --diff-filter=d $BASE_SHA ${{ github.sha }})
        CHANGED_PY_FILES=$(echo "$CHANGED_FILES" | grep -E "\.py$" || true)

        # Run black on changed files if any exist
        if [ -n "$CHANGED_PY_FILES" ]; then
          echo "$CHANGED_PY_FILES" | xargs black --check --diff --skip-string-normalization
        else
          echo "No Python files changed"
        fi
