name: Run unit tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Enable caching
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true

      - name: Set up Python
        run: uv venv --python 3.11

      - name: Install dependencies from uv.lock
        run: uv sync --frozen --extra dev

      - name: Run tests (coverage enabled)
        env:
          PYTHONPATH: ${{ env.PYTHONPATH }}:$PWD
        run: uv run pytest
