name: Run unit tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: conda-incubator/setup-miniconda@v3
        with:
          activate-environment: positronic
          use-only-tar-bz2: true
      - name: Cache conda
        uses: actions/cache@v3
        env:
          # Increase this value to reset cache if environment.yaml has not changed
          CACHE_NUMBER: 0
        with:
          path: ${{ env.CONDA }}/envs
          key:
            conda-${{ runner.os }}--${{ runner.arch }}--${{
            hashFiles('environment.yaml') }}-${{ env.CACHE_NUMBER }}
        id: cache
      - name: Install dependencies
        run: conda env update -n positronic -f environment.yaml
        if: steps.cache.outputs.cache-hit != 'true'
      - name: Run tests
        shell: bash -l {0}
        run: |
          conda run -n positronic pytest
