name: Run unit tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Enable caching
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true

      - name: Set up Python
        run: uv venv --python 3.11

      - name: Install dependencies from uv.lock
        run: uv sync --frozen --extra dev

      - name: "Run tests (coverage: term, html)"
        env:
          PYTHONPATH: ${{ env.PYTHONPATH }}:$PWD
        run: uv run pytest --cov-report=html

      - name: Coverage summary (job summary)
        if: always()
        run: uv run coverage report -m >> $GITHUB_STEP_SUMMARY

      - name: Upload coverage HTML artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: coverage-html
          path: htmlcov
